services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # Cambia esta contraseña por seguridad
      MYSQL_DATABASE: bd-prueba  # Nombre de la base de datos inicial
      MYSQL_USER: user           # Usuario de la base de datos
      MYSQL_PASSWORD: 12345      # Contraseña del usuario
    ports:
      - "3306:3306" # Mapea el puerto 3306 del contenedor al host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql # Montar el archivo SQL
    networks:
      - my_network

volumes:
  mysql_data:
    driver: local

networks:
  my_network:
    driver: bridge